# Generated by Django 6.1.1 on 2026-09-30 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='blockchain_document_id',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='verifier_name',
        ),
        migrations.AddField(
            model_name='verification',
            name='verifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Marksheet', 'Marksheet'), ('Certificate', 'Certificate'), ('Bonafide', 'Bonafide Certificate'), ('Internship', 'Internship Certificate'), ('Identity', 'Identity Document')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='sha256_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Blockchain Registration'), ('Registered', 'Registered on Blockchain')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='verification',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='result',
            field=models.BooleanField(),
        ),
    ]
