# Generated by Django 6.1.1 on 2026-09-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_blockchain_document_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
